name: BE CI & Auto Merge & Notify

on:
  push:
    branches: [BE]
  pull_request:
    branches: [BE]

jobs:
  build:
    name: ðŸš€ Build App
    runs-on: windows-latest

    permissions:
      contents: read
      pull-requests: write
      security-events: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Console App vÃ o thÆ° má»¥c BuildOutput
        run: dotnet publish ./Server/Server.csproj -c Release -o ./BuildOutput --self-contained false -r win-x64

      # Merge vÃ o main náº¿u test pass
      - name: Auto merge BE into main
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git fetch origin main || git checkout -b main
          git checkout main
          git pull origin main || echo "No remote main yet"

          git merge origin/be --no-ff --allow-unrelated-histories -m "Auto merge BE into main after successful build"

          # Push báº±ng token
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/thuangf45/CPSSFA.git main

