name: BE CI & Auto Merge & Notify

on:
  push:
    branches: [BE]
  pull_request:
    branches: [BE]

jobs:
  build:
    name: üöÄ Build App
    runs-on: windows-latest

    permissions:
      contents: read
      pull-requests: write
      security-events: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Console App v√†o th∆∞ m·ª•c BuildOutput
        run: dotnet publish ./Server/Server.csproj -c Release -o ./BuildOutput --self-contained false -r win-x64

      # Merge v√†o main n·∫øu test pass
      - name: Auto merge BE into main
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Checkout main
          git fetch origin main
          git checkout main

          # Merge branch BE v√†o main
          git merge origin/BE --no-ff --allow-unrelated-histories -m "Auto merge BE into main after successful build"

          # Push b·∫±ng token
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/thuangf45/CPSSFA.git main

